language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=table
  # GITHUB_RELEASE_TOKEN
  - secure: Su8UzatWB38lxteNZ4M/EEJKH/gposD0TrCdsTVzXgOpEprvpMCbhfEE/khV/wksaDcfsk5NRO3yFQ6TylWwPVpLIvQysEve2UmcfSTGHn1YH5+LxzpAlnMYSEYYjZO+DhLk/UeY/pt/0zDliOLL/DyR1XgC7t+z1kRP1vvd5OUuecY2GLZ4idWLOIaXmaaWCEyRGe+AkZiY+VgNJ2ewEypb2/1zBeyszvfvLLPpVBgIRjYpFP8n5qHmyHDCJMoj7G20YTw/Zo8PoyQWeW+0Mi7Yi3q8p+6w31EhgABUPXpNB8oHqmwyWMngOJdIywEDywGUO70vYPelT5dckB+nkJTSJvJP4aL64jJHMTlsasyZGA2I2S8ZxTofNiPIAjiqsLnEMIAljEtfaGHjMrJ5Pu5c+RTiOsVuDWSqPEAtoR9Xklw4rJwJbYA+t/X+DnM+qEU+qiXGnM9dcCMJmUqbPFi2iTNWZLg+/UIPM2yWMgFMhUgvOOAArY+ujvdSAkjnXzPetTfiA7sga9lzIIPMihXxARHNmMYms8EKqSvnrVPI4DoRK8/4h2hP2VCrRAOXKQtMOhg+3TreAPGl6YSEoJgIduxDzLda6tXb100lzVY5aHDI7eo6XioFhR7K3jX1rHKbwuXbbiJkKBrMwjdHk9t2AbWvLt1rm2pXlptu9Dw=
