language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - bower_components
addons:
  apt:
    packages:
    - oracle-java8-installer
  sauce_connect:
    username: Desire2Learn
  jwt:
    secure: ckU25LXR0YXAyr5F+w3LwR3vZQuxH1dJ9vELw7pdK3YRvPTCgaxoclkoSroVJOlBUmnm3dD9KEcVGCNyMFQdFEGItNt9vTnI7GH6Sm4q7TPzbLyga64y5DCsQljZQn+w0GyViAMkFaN5LZrQsBr+t7pnHilIsin/ARO4u4+/WAdb1x5ktmeg9SKYXWMB8uQEYkRPW0Wqp+WE5Z4jQrRsw0/o4KFWxms8qyyXO0dAfEYSOXZkdmfk2jbI+bm8T9duxmwqyQV89L+xx03Cdyx06D7EEsN8b0logyg6HWD0bjGLdmYPatR4e7g+NV8lrUI9y8nYQCMwsE3GGNUf/G/yDFQ7ADdh8vF4OZczek1d4uhFDEHfeywLgURmaj5e6hiywCwOK5bZWXiBD3+5mCmFf7OAmFSHigeQuNfpIjMogcsm5vJ4IFC2psudAmOJqGSX+S3idsJO+A2C9AXkCcYKh2cI5NrzwzLDwbljFyPmt3Ls0d5YVcey0XMummUlsEeQEQb009aOoiEXZmp2tMGQZL/mvEM1kjbtzYlfFMrt/WxnMaYY8wDicyBqOndRdGtivEoEe2JzJiqJ9NmjZe/M3CVb9eorExEN+TPT+qAgRsGbTKp4u24WG9qmWAYpeSrC7f6QFT4ED4UfDDABRIrIa/urilDyyX89Ic6xhPBdVGI=
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- export PATH=$JAVA_HOME/bin:$PATH
script:
- concurrently -p name -n lint:js,lint:wc,galen,wct "npm run test:lint:js" "npm run
  test:lint:wc" "npm run test:galen" "wct --skip-plugin local"
