cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache/bower"

stages:
  - test
  - name: galen test
    if: type = pull_request

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 10.11.0
      install:
        - npm ci
      script:
        - concurrently -p name -n lint,polymer:test "npm run lint" "polymer test --skip-plugin local"
    - stage: galen test
      language: node_js
      node_js:
        - 10.11.0
      addons:
        apt:
          packages:
          - oracle-java8-installer
      install:
        - npm ci
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
        - export PATH=$JAVA_HOME/bin:$PATH
      script:
        - npm run test:galen:sauce
      after_script:
        - pip install --user awscli
        - aws s3 sync reports s3://farnsworth-travis-ci-artifacts/BrightspaceUI/table/$TRAVIS_BUILD_NUMBER
