language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - bower_components
addons:
  apt:
    packages:
    - oracle-java8-installer
  jwt:
    # SAUCE_ACCESS_KEY
    secure: tHJGSWQW7bBh614jdQhyIuJD1nbx/CtEQqZGDeeHE0EWgPGvZJNg2aDgSb89sVba/YGdodlubXqaKLtkFX1MravlMG7PjTbRgaHCRlLVAEZrkg7F9IUvdy5vTM4HEf+N6hHoHsiXc4abzu3I33dfe8iih3Us2qs3vhg+rdBVjbVk/Hx4UK1P/DUKhLGvC5lESj9xzZAOnHf5uIEdHtvgKubPmaJKCeFyM4VBbXhj1wM56FxQvGe8NJLlk/DvGbsaI1ekeg0r1W1C4rmCJjjycPMPC7bClho1VEQ+zQccG++YKGd26Ac7rsLwyzRXOxBlmMzA3yC84R1CRN7+w/wLseF9NXZj4GJZ2a/Ij8fdl7sYFJsA6lJXwMAI/JOMtL99ebipkaulYaVRIipEvZAfxOqRLlRpR9evrLHL7YnIVaMo1qrBOrP2ptUwZQnQJm6IMam3xsWIOliwaFvEBDm/2DW4BDSlZC0FVmO9VdYLQStLsYHswWV982ZvNcaB/+Xu6k47hL0yNofhDAcpgVr9tw5URxg3kEa3EClLSRXTX+CeDFQ1qRb3mCrTUzz9SKg0Z7i0nH+T0H/SQSdqmsk+6lORYkm/y8FgenNTeb6BAl9hLza2OjDmZjD+/P785nzJZbNGpsstdO1qQXIN3gNdSywNOiU4U9qkw7gr2wq334U=
  artifacts:
    key:
      secure: IWkqgI4Fm1T4hr+riIzL0j3Zg+Yl3znkv6q6EyHhRnIWbSKkLHcqrnhOUmqdv/6DyRfDsXJf8sJHqiwV2guvQsf1InkSbIFleM5/myl80G3Y91QthnRZKVuFvza0xbgoI+zyOvI5AVgNmFUP6y1h4xh0ho+aajPcL9DB4NBTMp6uk7ioaaUELVYNhngMdiXk9FQWpSD2y+zg94SIXSQKI5Dn+roCi+n0cmmpz12gyEUFsRCNAsidtOaDSP35heGPOLjihJuGTWahN1jO06kvE/kQ4r2K6omKK1ff1k2tFY+wtPttVYM/92fgURoMrpoLh6OzO4nko95WbbjCMQmdK9sjOUnbyZhSjeVLOAxVTj5oRz/X3GqSUcvARuj63q+fniphODkOgkifDFd5JeDqHLMBsOEJf6GSZW3Gy9bdfSW/JH+dWO5FJBuFDtj9qQlanOaUhUmIhj9z0Fx5xBH6D2FsmknNPWVuVNbtFcu32zBQ5pOJ7Mav1M6TyQtBbxc9eZmhFKN70E9R6PjjWUXaGzts5MNJCY4bQ5LTKaUdfiAoB9KYDIz9fa4ugvU91HTeG6136AKy9OjPbRATz2vV+i9cW0sTvMjYCGRUxRStCa4aHD7oBjs9HtEA1/RVo8US1GizPwe27z1GYQuKmVPQ44lKUDWJr/VTB6EMDHTF71U=
    secret:
      secure: ICiS31Zx5VSu0rcnVKD30r9ZvFUlrYawiC0F7itaTqyhynN+lWRyI2oOXrVReu04wiIzrLQtfm4ZUrHATp7PTdpEzz28fpn5f8zybdWkkYrcAD+hLsZuTd/QrbOKmkdS6hCNgS0Qx1ZJmUyHYDeE/uhSb1dfx/cKe3ntqWFFHj/HhAfHBpWNBnYn5mqqXO1du0xsRvo16pSG4QukS8cLSWQj1dL7c9cXQEi0JljBJbY2UiD2nryoFU585+enKaDvG+IP+CFIpoqVmrcIqGGESyoTg/8Zlnn1kR9pm8+kUJCxa1hb/xoYWAIYr0vYpRQ5rlF+999rBEEqQjDjgTxqneLgwRYCGib8FHZZI9yJQFzfNbovGbmg7EqlgxwMlIUqK+iZZswg15y2L9ND+/mzRT3raIprDlMcEpuuUfqh1TqYNejxN02BjD63hb7lMLSysjPJUs0sPg5sLYvc2RfI4WHdkmhoKMEo0eQxdD7RfMpNd29Em+Mb4bL7WTCAqvkacG4o76UGQ3n9fpIWrt6jsezmIeEr/pDdeQARd09uYCDO87cklUv16PPOFi0vPxnbF8DaN29Hf/el4OANgj3mAgEUTRSyZPic+SZtKP+iJ/WSvL/4zT06px2AihUYCo/0g2S09OWFbM/cKAv7f/nSfDiAtAbWjV4rp4qUc5eaIqA=
    bucket: sequence-viewer-artifacts
    paths:
    - reports
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- export PATH=$JAVA_HOME/bin:$PATH
script:
- concurrently -p name -n lint:js,lint:wc,galen,wct "npm run test:lint:js" "npm run test:lint:wc" "wct --skip-plugin local"
- npm run test:galen:sauce
env:
  global:
    SAUCE_USERNAME: Desire2Learn
